server:
  port: 8080

spring:
  application:
    name: itsm-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/itsm_db
    username: elifnisatosun
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG